version: '3.1'

services:
  blog_strap_api:
    container_name: db_practe_docker
    hostname: db_practe_docker
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: practice_docker
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ~/.PostgresData/postgresonly/blog_strap_api:/var/lib/postgresql/data/pgdata
    ports: 
      - 5432:5432